### ISSUE TITLE
plasma-web: Popup: redesign & refactoring ( PLASMA-2068 )

### ISSUE THREAD

**Issue by Yeti-or** [salute-developers/plasma#589]

**Comment by Salute-Eva** [comment]
🚀 This Issue is included in version: @salutejs/plasma-b2c@1.240.0-dev.0, @salutejs/plasma-core@1.137.0-dev.0, @salutejs/plasma-hope@1.238.0-dev.0, @salutejs/plasma-icons@1.168.0-dev.0, @salutejs/plasma-new-hope@0.9.0-dev.0, @salutejs/plasma-sb-utils@0.135.0-dev.0, @salutejs/plasma-temple-docs@0.177.0-dev.0, @salutejs/plasma-temple@1.186.0-dev.0, @salutejs/plasma-ui-docs@0.226.0-dev.0, @salutejs/plasma-ui@1.218.0-dev.0, @salutejs/plasma-web-docs@0.194.0-dev.0, @salutejs/plasma-web@1.240.0-dev.0, @salutejs/plasma-website@0.202.0-dev.0 🚀

**Comment by Salute-Eva** [comment]
🚀 This Issue is included in version: @salutejs/plasma-b2c@1.240.0-dev.0, @salutejs/plasma-core@1.137.0-dev.0, @salutejs/plasma-hope@1.238.0-dev.0, @salutejs/plasma-icons@1.168.0-dev.0, @salutejs/plasma-new-hope@0.9.0-dev.0, @salutejs/plasma-sb-utils@0.135.0-dev.0, @salutejs/plasma-temple-docs@0.177.0-dev.0, @salutejs/plasma-temple@1.186.0-dev.0, @salutejs/plasma-ui-docs@0.226.0-dev.0, @salutejs/plasma-ui@1.218.0-dev.0, @salutejs/plasma-web-docs@0.194.0-dev.0, @salutejs/plasma-web@1.240.0-dev.0, @salutejs/plasma-website@0.202.0-dev.0 🚀

**Comment by Salute-Eva** [comment]
🚀 This Issue is included in version: @salutejs/plasma-b2c@1.240.0-dev.0, @salutejs/plasma-core@1.137.0-dev.0, @salutejs/plasma-hope@1.238.0-dev.0, @salutejs/plasma-icons@1.168.0-dev.0, @salutejs/plasma-new-hope@0.9.0-dev.0, @salutejs/plasma-sb-utils@0.135.0-dev.0, @salutejs/plasma-temple-docs@0.177.0-dev.0, @salutejs/plasma-temple@1.186.0-dev.0, @salutejs/plasma-ui-docs@0.226.0-dev.0, @salutejs/plasma-ui@1.218.0-dev.0, @salutejs/plasma-web-docs@0.194.0-dev.0, @salutejs/plasma-web@1.240.0-dev.0, @salutejs/plasma-website@0.202.0-dev.0 🚀

**Comment by Salute-Eva** [comment]
🚀 This Issue is included in version: @salutejs/plasma-b2c@1.240.0-dev.0, @salutejs/plasma-core@1.137.0-dev.0, @salutejs/plasma-hope@1.238.0-dev.0, @salutejs/plasma-icons@1.168.0-dev.0, @salutejs/plasma-new-hope@0.9.0-dev.0, @salutejs/plasma-sb-utils@0.135.0-dev.0, @salutejs/plasma-temple-docs@0.177.0-dev.0, @salutejs/plasma-temple@1.186.0-dev.0, @salutejs/plasma-ui-docs@0.226.0-dev.0, @salutejs/plasma-ui@1.218.0-dev.0, @salutejs/plasma-web-docs@0.194.0-dev.0, @salutejs/plasma-web@1.240.0-dev.0, @salutejs/plasma-website@0.202.0-dev.0 🚀

**Comment by Salute-Eva** [comment]
🚀 This Issue is included in version: @salutejs/plasma-b2c@1.240.0, @salutejs/plasma-core@1.137.0, @salutejs/plasma-hope@1.238.0, @salutejs/plasma-icons@1.168.0, @salutejs/plasma-new-hope@0.9.0, @salutejs/plasma-sb-utils@0.135.0, @salutejs/plasma-temple-docs@0.177.0, @salutejs/plasma-temple@1.186.0, @salutejs/plasma-tokens-native@1.14.0, @salutejs/plasma-ui-docs@0.226.0, @salutejs/plasma-ui@1.218.0, @salutejs/plasma-web-docs@0.194.0, @salutejs/plasma-web@1.240.0, @salutejs/plasma-website@0.202.0 🚀
